/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./dist/**/*.{html,js}"],
  darkMode: ["class"],
  theme: {
    extend: {
      colors: {
        neutral: {
          1100: "#000000",
          1000: "#1b1c2f",
          900: "#302f42",
          800: "#524a72",
          700: "#67627c",
          600: "#808299",
          500: "#a0a2ad",
          400: "#a4a6b2",
          300: "#bbbfcc",
          200: "#e8ebf2",
          100: "#f7f8ff",
          0: "#ffffff",
          dark: {
            90: "rgba(0, 0, 0, 0.9)",
            80: "rgba(0, 0, 0, 0.8)",
            70: "rgba(0, 0, 0, 0.7)",
            60: "rgba(0, 0, 0, 0.6)",
            50: "rgba(0, 0, 0, 0.5)",
            40: "rgba(0, 0, 0, 0.4)",
            30: "rgba(0, 0, 0, 0.3)",
            20: "rgba(0, 0, 0, 0.2)",
            10: "rgba(0, 0, 0, 0.1)",
            0: "rgba(0, 0, 0, 0)",
          },
          light: {
            90: "rgba(255, 255, 255, 0.9)",
            80: "rgba(255, 255, 255, 0.8)",
            70: "rgba(255, 255, 255, 0.7)",
            60: "rgba(255, 255, 255, 0.6)",
            50: "rgba(255, 255, 255, 0.5)",
            40: "rgba(255, 255, 255, 0.4)",
            30: "rgba(255, 255, 255, 0.3)",
            20: "rgba(255, 255, 255, 0.2)",
            10: "rgba(255, 255, 255, 0.1)",
            0: "rgba(255, 255, 255, 0)",
          },
        },
        brand: {
          primary: "#5d57f6",
          secondary: "#b5e7ff",
          "primary-alpha-90": "rgba(93, 87, 246, 0.9)",
          "primary-alpha-80": "rgba(93, 87, 246, 0.8)",
          "primary-alpha-70": "rgba(93, 87, 246, 0.7)",
          "primary-alpha-60": "rgba(93, 87, 246, 0.6)",
          "primary-alpha-50": "rgba(93, 87, 246, 0.5)",
          "primary-alpha-40": "rgba(93, 87, 246, 0.4)",
          "primary-alpha-30": "rgba(93, 87, 246, 0.3)",
          "primary-alpha-20": "rgba(93, 87, 246, 0.2)",
          "primary-alpha-10": "rgba(93, 87, 246, 0.1)",
        },
        border: {
          base: "#e8ebf2",
          "layer-1": "#bbbfcc",
          "layer-2": "#a4a6b2",
          "layer-3": "#a0a2ad",
          muted: "#f7f8ff",
          inverse: "#302f42",
          transparent: "rgba(0, 0, 0, 0)",
          alpha: "rgba(0, 0, 0, 0.1)",
          "alpha-inverse": "rgba(255, 255, 255, 0.1)",
        },
        feedback: {
          "success-fg": "#16a34a",
          "warning-fg": "#d1b400",
          "error-fg": "#ef4444",
          "info-fg": "#5d57f6",
          "success-bg": "#bbf7d1",
          "warning-bg": "#feffc1",
          "error-bg": "#fee2e2",
          "info-bg": "#d6f0ff",
        },
        overlay: {
          base: "rgba(0, 0, 0, 0.6)",
          soft: "rgba(0, 0, 0, 0.3)",
          inverse: "rgba(255, 255, 255, 0.6)",
        },
        surface: {
          base: "#ffffff",
          "layer-1": "#f7f8ff",
          "layer-2": "#e8ebf2",
          "layer-3": "#bbbfcc",
          muted: "#e8ebf2",
          inverse: "#000000",
          transparent: "rgba(255, 255, 255, 0)",
          alpha: "rgba(255, 255, 255, 0.3)",
          "alpha-inverse": "rgba(0, 0, 0, 0.3)",
        },
        text: {
          primary: "#1b1c2f",
          secondary: "#524a72",
          tertiary: "#808299",
          disabled: "#a4a6b2",
          link: "#5d57f6",
          "link-hover": "rgba(93, 87, 246, 0.9)",
          "inverse-primary": "#ffffff",
          "inverse-secondary": "#e8ebf2",
          "inverse-tertiary": "#bbbfcc",
        },
        icon: {
          default: "#1b1c2f",
          hover: "#524a72",
          muted: "#808299",
          disabled: "#a4a6b2",
          primary: "#5d57f6",
          success: "#16a34a",
          warning: "#d1b400",
          error: "#ef4444",
          info: "#5d57f6",
          inverse: "#ffffff",
          "inverse-hover": "#e8ebf2",
        },
        button: {
          "primary-bg-default": "#5d57f6",
          "primary-bg-hover": "#0c4872",
          "primary-text-default": "#ffffff",
          "secondary-bg-default": "#edf0ff",
          "secondary-bg-hover": "#d6f0ff",
          "secondary-text-default": "#5d57f6",
          "tertiary-bg-default": "#ffffff",
          "tertiary-bg-hover": "#f7f8ff",
          "tertiary-text-default": "#1b1c2f",
          "tertiary-border-default": "#e8ebf2",
          "tertiary-border-hover": "#bbbfcc",
          "disabled-bg": "#e8ebf2",
          "disabled-text": "#a4a6b2",
        },
        field: {
          "text-default": "#1b1c2f",
          "text-hover": "#524a72",
          "text-mute": "#808299",
          "text-disabled": "#a4a6b2",
          "text-inverse": "#ffffff",
          "text-primary": "#5d57f6",
          "bg-default": "#ffffff",
          "bg-hover": "#f7f8ff",
          "bg-muted": "#e8ebf2",
          "bg-success": "#bbf7d1",
          "bg-warning": "#feffc1",
          "bg-error": "#fee2e2",
          "bg-info": "#d6f0ff",
          "border-default": "#e8ebf2",
          "border-hover": "#bbbfcc",
          "border-muted": "#f7f8ff",
          "border-success": "#16a34a",
          "border-warning": "#d1b400",
          "border-error": "#ef4444",
          "border-info": "#5d57f6",
        },
        interactive: {
          "text-default": "#1b1c2f",
          "text-hover": "#524a72",
          "text-mute": "#808299",
          "text-disabled": "#a4a6b2",
          "text-inverse": "#ffffff",
          "text-primary": "#5d57f6",
          "bg-default": "#ffffff",
          "bg-hover": "#f7f8ff",
          "bg-muted": "#e8ebf2",
          "bg-success": "#bbf7d1",
          "bg-warning": "#feffc1",
          "bg-error": "#fee2e2",
          "bg-info": "#d6f0ff",
          "border-default": "#e8ebf2",
          "border-hover": "#bbbfcc",
          "border-muted": "#f7f8ff",
          "border-success": "#16a34a",
          "border-warning": "#d1b400",
          "border-error": "#ef4444",
          "border-info": "#5d57f6",
        },
      },
      backgroundImage: {
        "button-gradient-1": "linear-gradient(90deg, #7974ff 0%, #e1c0fc 100%)",
        "button-gradient-2": "linear-gradient(90deg, #f7f8ff 0%, #e8ebf2 100%)",
        "button-gradient-3": "linear-gradient(90deg, #e8ebf2 0%, #e8ebf2 100%)",
      },
      boxShadow: {
        1: "0px 2px 4px 0 rgba(0, 0, 0, 0.1)",
        2: "0px 4px 12px 0 rgba(0, 0, 0, 0.1)",
        3: "0px 8px 24px 0 rgba(0, 0, 0, 0.1)",
        4: "0px 12px 48px 0 rgba(0, 0, 0, 0.1)",
        "button-1":
          "inset 0px 4px 3px 0px rgba(255, 255, 255, 0.4), 0px 8px 12px 0px rgba(23, 17, 168, 0.15), inset 4px 4px 10px 0px rgba(255, 255, 255, 0.4)",
        "button-1-2":
          "inset 0px 4px 3px 0px rgba(82, 82, 242, 0.3), inset 4px 4px 10px 0px rgba(255, 255, 255, 0.9), inset -4px -4px 10px 0px rgba(0, 0, 58, 0.2)",
        "button-2":
          "inset 0px 4px 3px 0px rgba(215, 218, 254, 0.6), 0px 8px 12px 0px rgba(12, 8, 109, 0.15), inset 4px 4px 8px 0px rgba(255, 255, 255, 1)",
        "button-2-2":
          "inset -4px -4px 10px 0px rgba(28, 49, 138, 0.2), inset 0px 4px 8px 0px rgba(198, 204, 238, 0.3), inset 4px 4px 5px 0px rgba(255, 255, 255, 0.5)",
        "button-3":
          "inset 0px 4px 3px 0px rgba(255, 255, 255, 0.4), inset 4px 4px 10px 0px rgba(255, 255, 255, 0.4)",
      },
      spacing: {
        "header-height": "48px",
        // clamp을 제거하고 기준점(기본 픽셀값)으로 완전 고정
        /* margin 토큰 */
        "margin-x-xs": "4px",
        "margin-y-xs": "4px",
        "margin-x-s": "8px",
        "margin-y-s": "8px",
        "margin-x-m": "12px",
        "margin-y-m": "12px",
        "margin-x-l": "16px",
        "margin-y-l": "16px",
        "margin-x-xl": "24px",
        "margin-y-xl": "24px",
        "margin-x-xxl": "48px",
        "margin-y-xxl": "48px",
        "margin-x-xxxl": "80px",
        "margin-y-xxxl": "80px",

        /* padding 토큰 */
        "padding-x-xxs": "4px",
        "padding-y-xxs": "4px",
        "padding-x-xs": "8px",
        "padding-y-xs": "8px",
        "padding-x-s": "12px",
        "padding-y-s": "12px",
        "padding-x-m": "16px",
        "padding-y-m": "16px",
        "padding-x-l": "20px",
        "padding-y-l": "20px",
        "padding-x-xl": "24px",
        "padding-y-xl": "24px",
        "padding-x-xxl": "32px",
        "padding-y-xxl": "32px",

        /* gap 토큰 */
        "gap-x-xs": "4px",
        "gap-y-xs": "4px",
        "gap-x-s": "8px",
        "gap-y-s": "8px",
        "gap-x-m": "12px",
        "gap-y-m": "12px",
        "gap-x-l": "16px",
        "gap-y-l": "16px",
        "gap-x-xl": "24px",
        "gap-y-xl": "24px",
      },
    },
  },
  plugins: [
    // require('tailwindcss-animate'),
    function ({ addBase, addComponents, theme }) {
      // 1. Base Reset (순수 값으로 치환)
      addBase({
        ":root": {
          "--safe-bottom": "0px",
          "--dvh": "1vh",
          // svg 참조 때문에 넣음
          "--color-brand-primary": "#5d57f6",
          "--color-icon-default": "#1b1c2f",
          "--color-icon-hover": "#524a72",
          "--color-icon-muted": "#808299",
          "--color-icon-disabled": "#a4a6b2",
          "--color-icon-primary": "#5d57f6",
          "--color-icon-success": "#16a34a",
          "--color-icon-warning": "#d1b400",
          "--color-icon-error": "#ef4444",
          "--color-icon-info": "#5d57f6",
          "--color-icon-inverse": "#ffffff",
        },
        "@supports (height: 1dvh)": {
          ":root": {
            "--dvh": "1dvh",
          },
        },
        "html, body": {
          width: "100%",
          height: "100%",
          backgroundColor: "#ffffff", // surface-base 하드코딩
          color: "#1b1c2f", // text-primary 하드코딩
          overflow: "hidden",
        },
        html: {
          paddingBottom: "var(--safe-bottom)",
        },
        "html.no-safe-padding": {
          paddingBottom: "0px !important",
        },
        "input, textarea": {
          "-webkit-user-select": "text",
          "user-select": "text",
        },
        img: {
          "-webkit-user-drag": "none",
          "-webkit-touch-callout": "none",
        },
        button: {
          cursor: "pointer",
        },
        "button:disabled": {
          cursor: "default",
        },
        "input::-webkit-outer-spin-button, input::-webkit-inner-spin-button": {
          "-webkit-appearance": "none",
          margin: "0",
        },
        'input[type="number"]': {
          "-moz-appearance": "textfield",
        },
      });

      // 2. Typography & Custom Components (순수 값으로 치환)
      addComponents({
        ".allow-copy": {
          "-webkit-user-select": "text",
          "user-select": "text",
          "-webkit-touch-callout": "default",
        },
        ".swiper-pagination-bullet": {
          backgroundColor: "#a4a6b2 !important", // icon-disabled 하드코딩
        },
        ".swiper-pagination-bullet-active": {
          backgroundColor: "#5d57f6 !important", // brand-primary 하드코딩
        },
        ".swiper-pagination-bullets, .swiper-pagination-horizontal": {
          height: "8px",
          display: "flex",
          justifyContent: "center",
        },
        // Typography
        ".text-badge": {
          fontWeight: "700",
          fontSize: "8.25px",
          lineHeight: "100%",
          letterSpacing: "0",
        },
        ".text-hero": {
          fontWeight: "700",
          fontSize: "72px",
          lineHeight: "125%",
          letterSpacing: "0",
        },
        ".text-headline-l": {
          fontWeight: "700",
          fontSize: "36px",
          lineHeight: "125%",
          letterSpacing: "0",
        },
        ".text-headline-m": {
          fontWeight: "700",
          fontSize: "32px",
          lineHeight: "125%",
          letterSpacing: "0",
        },
        ".text-headline-s": {
          fontWeight: "700",
          fontSize: "28px",
          lineHeight: "125%",
          letterSpacing: "0",
        },
        ".text-title-1": {
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "140%",
          letterSpacing: "0",
        },
        ".text-title-2": {
          fontWeight: "700",
          fontSize: "20px",
          lineHeight: "140%",
          letterSpacing: "0",
        },
        ".text-title-3": {
          fontWeight: "700",
          fontSize: "18px",
          lineHeight: "140%",
          letterSpacing: "0",
        },
        ".text-label-l": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "24px",
          letterSpacing: "0",
        },
        ".text-label-m": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "24px",
          letterSpacing: "0",
        },
        ".text-label-s": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "20px",
          letterSpacing: "0",
        },
        ".text-body-1": {
          fontWeight: "400",
          fontSize: "16px",
          lineHeight: "180%",
          letterSpacing: "0",
        },
        ".text-body-2": {
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "180%",
          letterSpacing: "0",
        },
        ".text-button-1": {
          fontWeight: "700",
          fontSize: "16px",
          lineHeight: "24px",
          letterSpacing: "0",
        },
        ".text-button-2": {
          fontWeight: "700",
          fontSize: "14px",
          lineHeight: "20px",
          letterSpacing: "0",
        },
        ".text-button-3": {
          fontWeight: "700",
          fontSize: "12px",
          lineHeight: "20px",
          letterSpacing: "0",
        },
        ".text-caption-l": {
          fontWeight: "400",
          fontSize: "14px",
          lineHeight: "24px",
          letterSpacing: "0",
        },
        ".text-caption-m": {
          fontWeight: "400",
          fontSize: "12px",
          lineHeight: "20px",
          letterSpacing: "0",
        },
        ".text-caption-s": {
          fontWeight: "400",
          fontSize: "11px",
          lineHeight: "16px",
          letterSpacing: "0",
        },
        ".aspect-square": {
          display: "block",
          overflow: "hidden",
        },
        ".aspect-square::before": {
          content: '""',
          display: "block",
          paddingTop: "100%",
        },
        ".aspect-square > *": {
          position: "absolute",
          top: "0",
          left: "0",
          width: "100%",
          height: "100%",
          objectFit: "cover",
        },
        ".inset-0": {
          top: "0",
          left: "0",
          bottom: "0",
          right: "0",
        },
      });
    },
  ],
};
