/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMainRouteImport } from './routes/_authenticated/_main'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authRestoreRouteImport } from './routes/(auth)/restore'
import { Route as authPasswordRouteImport } from './routes/(auth)/password'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authByeRouteImport } from './routes/(auth)/bye'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedDailyIndexRouteImport } from './routes/_authenticated/daily/index'
import { Route as AuthenticatedAskIndexRouteImport } from './routes/_authenticated/ask/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedSocialSearchRouteImport } from './routes/_authenticated/social/search'
import { Route as AuthenticatedSocialRequestsRouteImport } from './routes/_authenticated/social/requests'
import { Route as AuthenticatedSocialBlockedRouteImport } from './routes/_authenticated/social/blocked'
import { Route as AuthenticatedReportHistoryRouteImport } from './routes/_authenticated/report/history'
import { Route as AuthenticatedDetailDateRouteImport } from './routes/_authenticated/detail/$date'
import { Route as AuthenticatedDailyWriteRouteImport } from './routes/_authenticated/daily/write'
import { Route as AuthenticatedAskChatRouteImport } from './routes/_authenticated/ask/chat'
import { Route as AuthenticatedAskArchiveRouteImport } from './routes/_authenticated/ask/archive'
import { Route as AuthenticatedAccountWithdrawRouteImport } from './routes/_authenticated/account/withdraw'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAccountPasswordRouteImport } from './routes/_authenticated/account/password'
import { Route as AuthenticatedMainSocialRouteImport } from './routes/_authenticated/_main/social'
import { Route as AuthenticatedMainReportRouteImport } from './routes/_authenticated/_main/report'
import { Route as AuthenticatedMainCalendarRouteImport } from './routes/_authenticated/_main/calendar'
import { Route as authSignupTermsRouteImport } from './routes/(auth)/signup/terms'
import { Route as authSignupPasswordRouteImport } from './routes/(auth)/signup/password'
import { Route as authSignupEmailVerificationRouteImport } from './routes/(auth)/signup/emailVerification'
import { Route as authSignupEmailRouteImport } from './routes/(auth)/signup/email'
import { Route as authPasswordVerifyRouteImport } from './routes/(auth)/password/verify'
import { Route as authPasswordResetRouteImport } from './routes/(auth)/password/reset'
import { Route as authPasswordForgotRouteImport } from './routes/(auth)/password/forgot'
import { Route as authOnboardingProfileRouteImport } from './routes/(auth)/onboarding/profile'
import { Route as authOnboardingIntroRouteImport } from './routes/(auth)/onboarding/intro'
import { Route as authOnboardingCategoryRouteImport } from './routes/(auth)/onboarding/category'
import { Route as AuthenticatedReportMonthlyV2PeriodRouteImport } from './routes/_authenticated/report/monthly-v2.$period'
import { Route as AuthenticatedReportReportTypePeriodRouteImport } from './routes/_authenticated/report/$reportType.$period'
import { Route as AuthenticatedFlagReportReportIdRouteImport } from './routes/_authenticated/flag/report.$reportId'
import { Route as AuthenticatedFlagCommentCommentIdRouteImport } from './routes/_authenticated/flag/comment.$commentId'
import { Route as AuthenticatedDailyReportReportIdRouteImport } from './routes/_authenticated/daily/report.$reportId'
import { Route as authAuthProviderCallbackRouteImport } from './routes/(auth)/auth.$provider.callback'
import { Route as AuthenticatedReportHistoryReportTypeReportIdRouteImport } from './routes/_authenticated/report/history.$reportType.$reportId'
import { Route as AuthenticatedDetailDatePostIdLikesRouteImport } from './routes/_authenticated/detail/$date.$postId.likes'
import { Route as AuthenticatedDetailDatePostIdCommentsRouteImport } from './routes/_authenticated/detail/$date.$postId.comments'
import { Route as AuthenticatedMainSocialPostIdLikesRouteImport } from './routes/_authenticated/_main/social/$postId.likes'
import { Route as AuthenticatedMainSocialPostIdCommentsRouteImport } from './routes/_authenticated/_main/social/$postId.comments'
import { Route as AuthenticatedDetailDatePostIdCommentsCommentIdLikesRouteImport } from './routes/_authenticated/detail/$date.$postId.comments.$commentId.likes'
import { Route as AuthenticatedMainSocialPostIdCommentsCommentIdLikesRouteImport } from './routes/_authenticated/_main/social/$postId.comments.$commentId.likes'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMainRoute = AuthenticatedMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authRestoreRoute = authRestoreRouteImport.update({
  id: '/(auth)/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const authPasswordRoute = authPasswordRouteImport.update({
  id: '/(auth)/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authByeRoute = authByeRouteImport.update({
  id: '/(auth)/bye',
  path: '/bye',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDailyIndexRoute = AuthenticatedDailyIndexRouteImport.update({
  id: '/daily/',
  path: '/daily/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskIndexRoute = AuthenticatedAskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSocialSearchRoute =
  AuthenticatedSocialSearchRouteImport.update({
    id: '/social/search',
    path: '/social/search',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSocialRequestsRoute =
  AuthenticatedSocialRequestsRouteImport.update({
    id: '/social/requests',
    path: '/social/requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSocialBlockedRoute =
  AuthenticatedSocialBlockedRouteImport.update({
    id: '/social/blocked',
    path: '/social/blocked',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportHistoryRoute =
  AuthenticatedReportHistoryRouteImport.update({
    id: '/report/history',
    path: '/report/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDetailDateRoute = AuthenticatedDetailDateRouteImport.update({
  id: '/detail/$date',
  path: '/detail/$date',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDailyWriteRoute = AuthenticatedDailyWriteRouteImport.update({
  id: '/daily/write',
  path: '/daily/write',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskChatRoute = AuthenticatedAskChatRouteImport.update({
  id: '/ask/chat',
  path: '/ask/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAskArchiveRoute = AuthenticatedAskArchiveRouteImport.update({
  id: '/ask/archive',
  path: '/ask/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountWithdrawRoute =
  AuthenticatedAccountWithdrawRouteImport.update({
    id: '/account/withdraw',
    path: '/account/withdraw',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountPasswordRoute =
  AuthenticatedAccountPasswordRouteImport.update({
    id: '/account/password',
    path: '/account/password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMainSocialRoute = AuthenticatedMainSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedMainRoute,
} as any)
const AuthenticatedMainReportRoute = AuthenticatedMainReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedMainRoute,
} as any)
const AuthenticatedMainCalendarRoute =
  AuthenticatedMainCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedMainRoute,
  } as any)
const authSignupTermsRoute = authSignupTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => authSignupRoute,
} as any)
const authSignupPasswordRoute = authSignupPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => authSignupRoute,
} as any)
const authSignupEmailVerificationRoute =
  authSignupEmailVerificationRouteImport.update({
    id: '/emailVerification',
    path: '/emailVerification',
    getParentRoute: () => authSignupRoute,
  } as any)
const authSignupEmailRoute = authSignupEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => authSignupRoute,
} as any)
const authPasswordVerifyRoute = authPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => authPasswordRoute,
} as any)
const authPasswordResetRoute = authPasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => authPasswordRoute,
} as any)
const authPasswordForgotRoute = authPasswordForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => authPasswordRoute,
} as any)
const authOnboardingProfileRoute = authOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authOnboardingRoute,
} as any)
const authOnboardingIntroRoute = authOnboardingIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => authOnboardingRoute,
} as any)
const authOnboardingCategoryRoute = authOnboardingCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => authOnboardingRoute,
} as any)
const AuthenticatedReportMonthlyV2PeriodRoute =
  AuthenticatedReportMonthlyV2PeriodRouteImport.update({
    id: '/report/monthly-v2/$period',
    path: '/report/monthly-v2/$period',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportReportTypePeriodRoute =
  AuthenticatedReportReportTypePeriodRouteImport.update({
    id: '/report/$reportType/$period',
    path: '/report/$reportType/$period',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlagReportReportIdRoute =
  AuthenticatedFlagReportReportIdRouteImport.update({
    id: '/flag/report/$reportId',
    path: '/flag/report/$reportId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFlagCommentCommentIdRoute =
  AuthenticatedFlagCommentCommentIdRouteImport.update({
    id: '/flag/comment/$commentId',
    path: '/flag/comment/$commentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDailyReportReportIdRoute =
  AuthenticatedDailyReportReportIdRouteImport.update({
    id: '/daily/report/$reportId',
    path: '/daily/report/$reportId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const authAuthProviderCallbackRoute =
  authAuthProviderCallbackRouteImport.update({
    id: '/(auth)/auth/$provider/callback',
    path: '/auth/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedReportHistoryReportTypeReportIdRoute =
  AuthenticatedReportHistoryReportTypeReportIdRouteImport.update({
    id: '/$reportType/$reportId',
    path: '/$reportType/$reportId',
    getParentRoute: () => AuthenticatedReportHistoryRoute,
  } as any)
const AuthenticatedDetailDatePostIdLikesRoute =
  AuthenticatedDetailDatePostIdLikesRouteImport.update({
    id: '/$postId/likes',
    path: '/$postId/likes',
    getParentRoute: () => AuthenticatedDetailDateRoute,
  } as any)
const AuthenticatedDetailDatePostIdCommentsRoute =
  AuthenticatedDetailDatePostIdCommentsRouteImport.update({
    id: '/$postId/comments',
    path: '/$postId/comments',
    getParentRoute: () => AuthenticatedDetailDateRoute,
  } as any)
const AuthenticatedMainSocialPostIdLikesRoute =
  AuthenticatedMainSocialPostIdLikesRouteImport.update({
    id: '/$postId/likes',
    path: '/$postId/likes',
    getParentRoute: () => AuthenticatedMainSocialRoute,
  } as any)
const AuthenticatedMainSocialPostIdCommentsRoute =
  AuthenticatedMainSocialPostIdCommentsRouteImport.update({
    id: '/$postId/comments',
    path: '/$postId/comments',
    getParentRoute: () => AuthenticatedMainSocialRoute,
  } as any)
const AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute =
  AuthenticatedDetailDatePostIdCommentsCommentIdLikesRouteImport.update({
    id: '/$commentId/likes',
    path: '/$commentId/likes',
    getParentRoute: () => AuthenticatedDetailDatePostIdCommentsRoute,
  } as any)
const AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute =
  AuthenticatedMainSocialPostIdCommentsCommentIdLikesRouteImport.update({
    id: '/$commentId/likes',
    path: '/$commentId/likes',
    getParentRoute: () => AuthenticatedMainSocialPostIdCommentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bye': typeof authByeRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRouteWithChildren
  '/password': typeof authPasswordRouteWithChildren
  '/restore': typeof authRestoreRoute
  '/signup': typeof authSignupRouteWithChildren
  '/onboarding/category': typeof authOnboardingCategoryRoute
  '/onboarding/intro': typeof authOnboardingIntroRoute
  '/onboarding/profile': typeof authOnboardingProfileRoute
  '/password/forgot': typeof authPasswordForgotRoute
  '/password/reset': typeof authPasswordResetRoute
  '/password/verify': typeof authPasswordVerifyRoute
  '/signup/email': typeof authSignupEmailRoute
  '/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/signup/password': typeof authSignupPasswordRoute
  '/signup/terms': typeof authSignupTermsRoute
  '/calendar': typeof AuthenticatedMainCalendarRoute
  '/report': typeof AuthenticatedMainReportRoute
  '/social': typeof AuthenticatedMainSocialRouteWithChildren
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/withdraw': typeof AuthenticatedAccountWithdrawRoute
  '/ask/archive': typeof AuthenticatedAskArchiveRoute
  '/ask/chat': typeof AuthenticatedAskChatRoute
  '/daily/write': typeof AuthenticatedDailyWriteRoute
  '/detail/$date': typeof AuthenticatedDetailDateRouteWithChildren
  '/report/history': typeof AuthenticatedReportHistoryRouteWithChildren
  '/social/blocked': typeof AuthenticatedSocialBlockedRoute
  '/social/requests': typeof AuthenticatedSocialRequestsRoute
  '/social/search': typeof AuthenticatedSocialSearchRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/ask': typeof AuthenticatedAskIndexRoute
  '/daily': typeof AuthenticatedDailyIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/auth/$provider/callback': typeof authAuthProviderCallbackRoute
  '/daily/report/$reportId': typeof AuthenticatedDailyReportReportIdRoute
  '/flag/comment/$commentId': typeof AuthenticatedFlagCommentCommentIdRoute
  '/flag/report/$reportId': typeof AuthenticatedFlagReportReportIdRoute
  '/report/$reportType/$period': typeof AuthenticatedReportReportTypePeriodRoute
  '/report/monthly-v2/$period': typeof AuthenticatedReportMonthlyV2PeriodRoute
  '/social/$postId/comments': typeof AuthenticatedMainSocialPostIdCommentsRouteWithChildren
  '/social/$postId/likes': typeof AuthenticatedMainSocialPostIdLikesRoute
  '/detail/$date/$postId/comments': typeof AuthenticatedDetailDatePostIdCommentsRouteWithChildren
  '/detail/$date/$postId/likes': typeof AuthenticatedDetailDatePostIdLikesRoute
  '/report/history/$reportType/$reportId': typeof AuthenticatedReportHistoryReportTypeReportIdRoute
  '/social/$postId/comments/$commentId/likes': typeof AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute
  '/detail/$date/$postId/comments/$commentId/likes': typeof AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bye': typeof authByeRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRouteWithChildren
  '/password': typeof authPasswordRouteWithChildren
  '/restore': typeof authRestoreRoute
  '/signup': typeof authSignupRouteWithChildren
  '/onboarding/category': typeof authOnboardingCategoryRoute
  '/onboarding/intro': typeof authOnboardingIntroRoute
  '/onboarding/profile': typeof authOnboardingProfileRoute
  '/password/forgot': typeof authPasswordForgotRoute
  '/password/reset': typeof authPasswordResetRoute
  '/password/verify': typeof authPasswordVerifyRoute
  '/signup/email': typeof authSignupEmailRoute
  '/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/signup/password': typeof authSignupPasswordRoute
  '/signup/terms': typeof authSignupTermsRoute
  '/calendar': typeof AuthenticatedMainCalendarRoute
  '/report': typeof AuthenticatedMainReportRoute
  '/social': typeof AuthenticatedMainSocialRouteWithChildren
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/withdraw': typeof AuthenticatedAccountWithdrawRoute
  '/ask/archive': typeof AuthenticatedAskArchiveRoute
  '/ask/chat': typeof AuthenticatedAskChatRoute
  '/daily/write': typeof AuthenticatedDailyWriteRoute
  '/detail/$date': typeof AuthenticatedDetailDateRouteWithChildren
  '/report/history': typeof AuthenticatedReportHistoryRouteWithChildren
  '/social/blocked': typeof AuthenticatedSocialBlockedRoute
  '/social/requests': typeof AuthenticatedSocialRequestsRoute
  '/social/search': typeof AuthenticatedSocialSearchRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/ask': typeof AuthenticatedAskIndexRoute
  '/daily': typeof AuthenticatedDailyIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/auth/$provider/callback': typeof authAuthProviderCallbackRoute
  '/daily/report/$reportId': typeof AuthenticatedDailyReportReportIdRoute
  '/flag/comment/$commentId': typeof AuthenticatedFlagCommentCommentIdRoute
  '/flag/report/$reportId': typeof AuthenticatedFlagReportReportIdRoute
  '/report/$reportType/$period': typeof AuthenticatedReportReportTypePeriodRoute
  '/report/monthly-v2/$period': typeof AuthenticatedReportMonthlyV2PeriodRoute
  '/social/$postId/comments': typeof AuthenticatedMainSocialPostIdCommentsRouteWithChildren
  '/social/$postId/likes': typeof AuthenticatedMainSocialPostIdLikesRoute
  '/detail/$date/$postId/comments': typeof AuthenticatedDetailDatePostIdCommentsRouteWithChildren
  '/detail/$date/$postId/likes': typeof AuthenticatedDetailDatePostIdLikesRoute
  '/report/history/$reportType/$reportId': typeof AuthenticatedReportHistoryReportTypeReportIdRoute
  '/social/$postId/comments/$commentId/likes': typeof AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute
  '/detail/$date/$postId/comments/$commentId/likes': typeof AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/bye': typeof authByeRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/onboarding': typeof authOnboardingRouteWithChildren
  '/(auth)/password': typeof authPasswordRouteWithChildren
  '/(auth)/restore': typeof authRestoreRoute
  '/(auth)/signup': typeof authSignupRouteWithChildren
  '/_authenticated/_main': typeof AuthenticatedMainRouteWithChildren
  '/(auth)/onboarding/category': typeof authOnboardingCategoryRoute
  '/(auth)/onboarding/intro': typeof authOnboardingIntroRoute
  '/(auth)/onboarding/profile': typeof authOnboardingProfileRoute
  '/(auth)/password/forgot': typeof authPasswordForgotRoute
  '/(auth)/password/reset': typeof authPasswordResetRoute
  '/(auth)/password/verify': typeof authPasswordVerifyRoute
  '/(auth)/signup/email': typeof authSignupEmailRoute
  '/(auth)/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/(auth)/signup/password': typeof authSignupPasswordRoute
  '/(auth)/signup/terms': typeof authSignupTermsRoute
  '/_authenticated/_main/calendar': typeof AuthenticatedMainCalendarRoute
  '/_authenticated/_main/report': typeof AuthenticatedMainReportRoute
  '/_authenticated/_main/social': typeof AuthenticatedMainSocialRouteWithChildren
  '/_authenticated/account/password': typeof AuthenticatedAccountPasswordRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/withdraw': typeof AuthenticatedAccountWithdrawRoute
  '/_authenticated/ask/archive': typeof AuthenticatedAskArchiveRoute
  '/_authenticated/ask/chat': typeof AuthenticatedAskChatRoute
  '/_authenticated/daily/write': typeof AuthenticatedDailyWriteRoute
  '/_authenticated/detail/$date': typeof AuthenticatedDetailDateRouteWithChildren
  '/_authenticated/report/history': typeof AuthenticatedReportHistoryRouteWithChildren
  '/_authenticated/social/blocked': typeof AuthenticatedSocialBlockedRoute
  '/_authenticated/social/requests': typeof AuthenticatedSocialRequestsRoute
  '/_authenticated/social/search': typeof AuthenticatedSocialSearchRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/ask/': typeof AuthenticatedAskIndexRoute
  '/_authenticated/daily/': typeof AuthenticatedDailyIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/(auth)/auth/$provider/callback': typeof authAuthProviderCallbackRoute
  '/_authenticated/daily/report/$reportId': typeof AuthenticatedDailyReportReportIdRoute
  '/_authenticated/flag/comment/$commentId': typeof AuthenticatedFlagCommentCommentIdRoute
  '/_authenticated/flag/report/$reportId': typeof AuthenticatedFlagReportReportIdRoute
  '/_authenticated/report/$reportType/$period': typeof AuthenticatedReportReportTypePeriodRoute
  '/_authenticated/report/monthly-v2/$period': typeof AuthenticatedReportMonthlyV2PeriodRoute
  '/_authenticated/_main/social/$postId/comments': typeof AuthenticatedMainSocialPostIdCommentsRouteWithChildren
  '/_authenticated/_main/social/$postId/likes': typeof AuthenticatedMainSocialPostIdLikesRoute
  '/_authenticated/detail/$date/$postId/comments': typeof AuthenticatedDetailDatePostIdCommentsRouteWithChildren
  '/_authenticated/detail/$date/$postId/likes': typeof AuthenticatedDetailDatePostIdLikesRoute
  '/_authenticated/report/history/$reportType/$reportId': typeof AuthenticatedReportHistoryReportTypeReportIdRoute
  '/_authenticated/_main/social/$postId/comments/$commentId/likes': typeof AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute
  '/_authenticated/detail/$date/$postId/comments/$commentId/likes': typeof AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bye'
    | '/login'
    | '/onboarding'
    | '/password'
    | '/restore'
    | '/signup'
    | '/onboarding/category'
    | '/onboarding/intro'
    | '/onboarding/profile'
    | '/password/forgot'
    | '/password/reset'
    | '/password/verify'
    | '/signup/email'
    | '/signup/emailVerification'
    | '/signup/password'
    | '/signup/terms'
    | '/calendar'
    | '/report'
    | '/social'
    | '/account/password'
    | '/account/profile'
    | '/account/withdraw'
    | '/ask/archive'
    | '/ask/chat'
    | '/daily/write'
    | '/detail/$date'
    | '/report/history'
    | '/social/blocked'
    | '/social/requests'
    | '/social/search'
    | '/account'
    | '/ask'
    | '/daily'
    | '/notifications'
    | '/search'
    | '/auth/$provider/callback'
    | '/daily/report/$reportId'
    | '/flag/comment/$commentId'
    | '/flag/report/$reportId'
    | '/report/$reportType/$period'
    | '/report/monthly-v2/$period'
    | '/social/$postId/comments'
    | '/social/$postId/likes'
    | '/detail/$date/$postId/comments'
    | '/detail/$date/$postId/likes'
    | '/report/history/$reportType/$reportId'
    | '/social/$postId/comments/$commentId/likes'
    | '/detail/$date/$postId/comments/$commentId/likes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bye'
    | '/login'
    | '/onboarding'
    | '/password'
    | '/restore'
    | '/signup'
    | '/onboarding/category'
    | '/onboarding/intro'
    | '/onboarding/profile'
    | '/password/forgot'
    | '/password/reset'
    | '/password/verify'
    | '/signup/email'
    | '/signup/emailVerification'
    | '/signup/password'
    | '/signup/terms'
    | '/calendar'
    | '/report'
    | '/social'
    | '/account/password'
    | '/account/profile'
    | '/account/withdraw'
    | '/ask/archive'
    | '/ask/chat'
    | '/daily/write'
    | '/detail/$date'
    | '/report/history'
    | '/social/blocked'
    | '/social/requests'
    | '/social/search'
    | '/account'
    | '/ask'
    | '/daily'
    | '/notifications'
    | '/search'
    | '/auth/$provider/callback'
    | '/daily/report/$reportId'
    | '/flag/comment/$commentId'
    | '/flag/report/$reportId'
    | '/report/$reportType/$period'
    | '/report/monthly-v2/$period'
    | '/social/$postId/comments'
    | '/social/$postId/likes'
    | '/detail/$date/$postId/comments'
    | '/detail/$date/$postId/likes'
    | '/report/history/$reportType/$reportId'
    | '/social/$postId/comments/$commentId/likes'
    | '/detail/$date/$postId/comments/$commentId/likes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/bye'
    | '/(auth)/login'
    | '/(auth)/onboarding'
    | '/(auth)/password'
    | '/(auth)/restore'
    | '/(auth)/signup'
    | '/_authenticated/_main'
    | '/(auth)/onboarding/category'
    | '/(auth)/onboarding/intro'
    | '/(auth)/onboarding/profile'
    | '/(auth)/password/forgot'
    | '/(auth)/password/reset'
    | '/(auth)/password/verify'
    | '/(auth)/signup/email'
    | '/(auth)/signup/emailVerification'
    | '/(auth)/signup/password'
    | '/(auth)/signup/terms'
    | '/_authenticated/_main/calendar'
    | '/_authenticated/_main/report'
    | '/_authenticated/_main/social'
    | '/_authenticated/account/password'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/withdraw'
    | '/_authenticated/ask/archive'
    | '/_authenticated/ask/chat'
    | '/_authenticated/daily/write'
    | '/_authenticated/detail/$date'
    | '/_authenticated/report/history'
    | '/_authenticated/social/blocked'
    | '/_authenticated/social/requests'
    | '/_authenticated/social/search'
    | '/_authenticated/account/'
    | '/_authenticated/ask/'
    | '/_authenticated/daily/'
    | '/_authenticated/notifications/'
    | '/_authenticated/search/'
    | '/(auth)/auth/$provider/callback'
    | '/_authenticated/daily/report/$reportId'
    | '/_authenticated/flag/comment/$commentId'
    | '/_authenticated/flag/report/$reportId'
    | '/_authenticated/report/$reportType/$period'
    | '/_authenticated/report/monthly-v2/$period'
    | '/_authenticated/_main/social/$postId/comments'
    | '/_authenticated/_main/social/$postId/likes'
    | '/_authenticated/detail/$date/$postId/comments'
    | '/_authenticated/detail/$date/$postId/likes'
    | '/_authenticated/report/history/$reportType/$reportId'
    | '/_authenticated/_main/social/$postId/comments/$commentId/likes'
    | '/_authenticated/detail/$date/$postId/comments/$commentId/likes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authByeRoute: typeof authByeRoute
  authLoginRoute: typeof authLoginRoute
  authOnboardingRoute: typeof authOnboardingRouteWithChildren
  authPasswordRoute: typeof authPasswordRouteWithChildren
  authRestoreRoute: typeof authRestoreRoute
  authSignupRoute: typeof authSignupRouteWithChildren
  authAuthProviderCallbackRoute: typeof authAuthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_main': {
      id: '/_authenticated/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/restore': {
      id: '/(auth)/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof authRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/password': {
      id: '/(auth)/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof authPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/bye': {
      id: '/(auth)/bye'
      path: '/bye'
      fullPath: '/bye'
      preLoaderRoute: typeof authByeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily/': {
      id: '/_authenticated/daily/'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask/': {
      id: '/_authenticated/ask/'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AuthenticatedAskIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social/search': {
      id: '/_authenticated/social/search'
      path: '/social/search'
      fullPath: '/social/search'
      preLoaderRoute: typeof AuthenticatedSocialSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social/requests': {
      id: '/_authenticated/social/requests'
      path: '/social/requests'
      fullPath: '/social/requests'
      preLoaderRoute: typeof AuthenticatedSocialRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social/blocked': {
      id: '/_authenticated/social/blocked'
      path: '/social/blocked'
      fullPath: '/social/blocked'
      preLoaderRoute: typeof AuthenticatedSocialBlockedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report/history': {
      id: '/_authenticated/report/history'
      path: '/report/history'
      fullPath: '/report/history'
      preLoaderRoute: typeof AuthenticatedReportHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/detail/$date': {
      id: '/_authenticated/detail/$date'
      path: '/detail/$date'
      fullPath: '/detail/$date'
      preLoaderRoute: typeof AuthenticatedDetailDateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily/write': {
      id: '/_authenticated/daily/write'
      path: '/daily/write'
      fullPath: '/daily/write'
      preLoaderRoute: typeof AuthenticatedDailyWriteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask/chat': {
      id: '/_authenticated/ask/chat'
      path: '/ask/chat'
      fullPath: '/ask/chat'
      preLoaderRoute: typeof AuthenticatedAskChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ask/archive': {
      id: '/_authenticated/ask/archive'
      path: '/ask/archive'
      fullPath: '/ask/archive'
      preLoaderRoute: typeof AuthenticatedAskArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/withdraw': {
      id: '/_authenticated/account/withdraw'
      path: '/account/withdraw'
      fullPath: '/account/withdraw'
      preLoaderRoute: typeof AuthenticatedAccountWithdrawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/password': {
      id: '/_authenticated/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthenticatedAccountPasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_main/social': {
      id: '/_authenticated/_main/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedMainSocialRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/_main/report': {
      id: '/_authenticated/_main/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedMainReportRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/_main/calendar': {
      id: '/_authenticated/_main/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedMainCalendarRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/(auth)/signup/terms': {
      id: '/(auth)/signup/terms'
      path: '/terms'
      fullPath: '/signup/terms'
      preLoaderRoute: typeof authSignupTermsRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/password': {
      id: '/(auth)/signup/password'
      path: '/password'
      fullPath: '/signup/password'
      preLoaderRoute: typeof authSignupPasswordRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/emailVerification': {
      id: '/(auth)/signup/emailVerification'
      path: '/emailVerification'
      fullPath: '/signup/emailVerification'
      preLoaderRoute: typeof authSignupEmailVerificationRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/email': {
      id: '/(auth)/signup/email'
      path: '/email'
      fullPath: '/signup/email'
      preLoaderRoute: typeof authSignupEmailRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/password/verify': {
      id: '/(auth)/password/verify'
      path: '/verify'
      fullPath: '/password/verify'
      preLoaderRoute: typeof authPasswordVerifyRouteImport
      parentRoute: typeof authPasswordRoute
    }
    '/(auth)/password/reset': {
      id: '/(auth)/password/reset'
      path: '/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof authPasswordResetRouteImport
      parentRoute: typeof authPasswordRoute
    }
    '/(auth)/password/forgot': {
      id: '/(auth)/password/forgot'
      path: '/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof authPasswordForgotRouteImport
      parentRoute: typeof authPasswordRoute
    }
    '/(auth)/onboarding/profile': {
      id: '/(auth)/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof authOnboardingProfileRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/(auth)/onboarding/intro': {
      id: '/(auth)/onboarding/intro'
      path: '/intro'
      fullPath: '/onboarding/intro'
      preLoaderRoute: typeof authOnboardingIntroRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/(auth)/onboarding/category': {
      id: '/(auth)/onboarding/category'
      path: '/category'
      fullPath: '/onboarding/category'
      preLoaderRoute: typeof authOnboardingCategoryRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/_authenticated/report/monthly-v2/$period': {
      id: '/_authenticated/report/monthly-v2/$period'
      path: '/report/monthly-v2/$period'
      fullPath: '/report/monthly-v2/$period'
      preLoaderRoute: typeof AuthenticatedReportMonthlyV2PeriodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report/$reportType/$period': {
      id: '/_authenticated/report/$reportType/$period'
      path: '/report/$reportType/$period'
      fullPath: '/report/$reportType/$period'
      preLoaderRoute: typeof AuthenticatedReportReportTypePeriodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flag/report/$reportId': {
      id: '/_authenticated/flag/report/$reportId'
      path: '/flag/report/$reportId'
      fullPath: '/flag/report/$reportId'
      preLoaderRoute: typeof AuthenticatedFlagReportReportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flag/comment/$commentId': {
      id: '/_authenticated/flag/comment/$commentId'
      path: '/flag/comment/$commentId'
      fullPath: '/flag/comment/$commentId'
      preLoaderRoute: typeof AuthenticatedFlagCommentCommentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily/report/$reportId': {
      id: '/_authenticated/daily/report/$reportId'
      path: '/daily/report/$reportId'
      fullPath: '/daily/report/$reportId'
      preLoaderRoute: typeof AuthenticatedDailyReportReportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/auth/$provider/callback': {
      id: '/(auth)/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof authAuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/report/history/$reportType/$reportId': {
      id: '/_authenticated/report/history/$reportType/$reportId'
      path: '/$reportType/$reportId'
      fullPath: '/report/history/$reportType/$reportId'
      preLoaderRoute: typeof AuthenticatedReportHistoryReportTypeReportIdRouteImport
      parentRoute: typeof AuthenticatedReportHistoryRoute
    }
    '/_authenticated/detail/$date/$postId/likes': {
      id: '/_authenticated/detail/$date/$postId/likes'
      path: '/$postId/likes'
      fullPath: '/detail/$date/$postId/likes'
      preLoaderRoute: typeof AuthenticatedDetailDatePostIdLikesRouteImport
      parentRoute: typeof AuthenticatedDetailDateRoute
    }
    '/_authenticated/detail/$date/$postId/comments': {
      id: '/_authenticated/detail/$date/$postId/comments'
      path: '/$postId/comments'
      fullPath: '/detail/$date/$postId/comments'
      preLoaderRoute: typeof AuthenticatedDetailDatePostIdCommentsRouteImport
      parentRoute: typeof AuthenticatedDetailDateRoute
    }
    '/_authenticated/_main/social/$postId/likes': {
      id: '/_authenticated/_main/social/$postId/likes'
      path: '/$postId/likes'
      fullPath: '/social/$postId/likes'
      preLoaderRoute: typeof AuthenticatedMainSocialPostIdLikesRouteImport
      parentRoute: typeof AuthenticatedMainSocialRoute
    }
    '/_authenticated/_main/social/$postId/comments': {
      id: '/_authenticated/_main/social/$postId/comments'
      path: '/$postId/comments'
      fullPath: '/social/$postId/comments'
      preLoaderRoute: typeof AuthenticatedMainSocialPostIdCommentsRouteImport
      parentRoute: typeof AuthenticatedMainSocialRoute
    }
    '/_authenticated/detail/$date/$postId/comments/$commentId/likes': {
      id: '/_authenticated/detail/$date/$postId/comments/$commentId/likes'
      path: '/$commentId/likes'
      fullPath: '/detail/$date/$postId/comments/$commentId/likes'
      preLoaderRoute: typeof AuthenticatedDetailDatePostIdCommentsCommentIdLikesRouteImport
      parentRoute: typeof AuthenticatedDetailDatePostIdCommentsRoute
    }
    '/_authenticated/_main/social/$postId/comments/$commentId/likes': {
      id: '/_authenticated/_main/social/$postId/comments/$commentId/likes'
      path: '/$commentId/likes'
      fullPath: '/social/$postId/comments/$commentId/likes'
      preLoaderRoute: typeof AuthenticatedMainSocialPostIdCommentsCommentIdLikesRouteImport
      parentRoute: typeof AuthenticatedMainSocialPostIdCommentsRoute
    }
  }
}

interface AuthenticatedMainSocialPostIdCommentsRouteChildren {
  AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute: typeof AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute
}

const AuthenticatedMainSocialPostIdCommentsRouteChildren: AuthenticatedMainSocialPostIdCommentsRouteChildren =
  {
    AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute:
      AuthenticatedMainSocialPostIdCommentsCommentIdLikesRoute,
  }

const AuthenticatedMainSocialPostIdCommentsRouteWithChildren =
  AuthenticatedMainSocialPostIdCommentsRoute._addFileChildren(
    AuthenticatedMainSocialPostIdCommentsRouteChildren,
  )

interface AuthenticatedMainSocialRouteChildren {
  AuthenticatedMainSocialPostIdCommentsRoute: typeof AuthenticatedMainSocialPostIdCommentsRouteWithChildren
  AuthenticatedMainSocialPostIdLikesRoute: typeof AuthenticatedMainSocialPostIdLikesRoute
}

const AuthenticatedMainSocialRouteChildren: AuthenticatedMainSocialRouteChildren =
  {
    AuthenticatedMainSocialPostIdCommentsRoute:
      AuthenticatedMainSocialPostIdCommentsRouteWithChildren,
    AuthenticatedMainSocialPostIdLikesRoute:
      AuthenticatedMainSocialPostIdLikesRoute,
  }

const AuthenticatedMainSocialRouteWithChildren =
  AuthenticatedMainSocialRoute._addFileChildren(
    AuthenticatedMainSocialRouteChildren,
  )

interface AuthenticatedMainRouteChildren {
  AuthenticatedMainCalendarRoute: typeof AuthenticatedMainCalendarRoute
  AuthenticatedMainReportRoute: typeof AuthenticatedMainReportRoute
  AuthenticatedMainSocialRoute: typeof AuthenticatedMainSocialRouteWithChildren
}

const AuthenticatedMainRouteChildren: AuthenticatedMainRouteChildren = {
  AuthenticatedMainCalendarRoute: AuthenticatedMainCalendarRoute,
  AuthenticatedMainReportRoute: AuthenticatedMainReportRoute,
  AuthenticatedMainSocialRoute: AuthenticatedMainSocialRouteWithChildren,
}

const AuthenticatedMainRouteWithChildren =
  AuthenticatedMainRoute._addFileChildren(AuthenticatedMainRouteChildren)

interface AuthenticatedDetailDatePostIdCommentsRouteChildren {
  AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute: typeof AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute
}

const AuthenticatedDetailDatePostIdCommentsRouteChildren: AuthenticatedDetailDatePostIdCommentsRouteChildren =
  {
    AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute:
      AuthenticatedDetailDatePostIdCommentsCommentIdLikesRoute,
  }

const AuthenticatedDetailDatePostIdCommentsRouteWithChildren =
  AuthenticatedDetailDatePostIdCommentsRoute._addFileChildren(
    AuthenticatedDetailDatePostIdCommentsRouteChildren,
  )

interface AuthenticatedDetailDateRouteChildren {
  AuthenticatedDetailDatePostIdCommentsRoute: typeof AuthenticatedDetailDatePostIdCommentsRouteWithChildren
  AuthenticatedDetailDatePostIdLikesRoute: typeof AuthenticatedDetailDatePostIdLikesRoute
}

const AuthenticatedDetailDateRouteChildren: AuthenticatedDetailDateRouteChildren =
  {
    AuthenticatedDetailDatePostIdCommentsRoute:
      AuthenticatedDetailDatePostIdCommentsRouteWithChildren,
    AuthenticatedDetailDatePostIdLikesRoute:
      AuthenticatedDetailDatePostIdLikesRoute,
  }

const AuthenticatedDetailDateRouteWithChildren =
  AuthenticatedDetailDateRoute._addFileChildren(
    AuthenticatedDetailDateRouteChildren,
  )

interface AuthenticatedReportHistoryRouteChildren {
  AuthenticatedReportHistoryReportTypeReportIdRoute: typeof AuthenticatedReportHistoryReportTypeReportIdRoute
}

const AuthenticatedReportHistoryRouteChildren: AuthenticatedReportHistoryRouteChildren =
  {
    AuthenticatedReportHistoryReportTypeReportIdRoute:
      AuthenticatedReportHistoryReportTypeReportIdRoute,
  }

const AuthenticatedReportHistoryRouteWithChildren =
  AuthenticatedReportHistoryRoute._addFileChildren(
    AuthenticatedReportHistoryRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedMainRoute: typeof AuthenticatedMainRouteWithChildren
  AuthenticatedAccountPasswordRoute: typeof AuthenticatedAccountPasswordRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountWithdrawRoute: typeof AuthenticatedAccountWithdrawRoute
  AuthenticatedAskArchiveRoute: typeof AuthenticatedAskArchiveRoute
  AuthenticatedAskChatRoute: typeof AuthenticatedAskChatRoute
  AuthenticatedDailyWriteRoute: typeof AuthenticatedDailyWriteRoute
  AuthenticatedDetailDateRoute: typeof AuthenticatedDetailDateRouteWithChildren
  AuthenticatedReportHistoryRoute: typeof AuthenticatedReportHistoryRouteWithChildren
  AuthenticatedSocialBlockedRoute: typeof AuthenticatedSocialBlockedRoute
  AuthenticatedSocialRequestsRoute: typeof AuthenticatedSocialRequestsRoute
  AuthenticatedSocialSearchRoute: typeof AuthenticatedSocialSearchRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAskIndexRoute: typeof AuthenticatedAskIndexRoute
  AuthenticatedDailyIndexRoute: typeof AuthenticatedDailyIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedDailyReportReportIdRoute: typeof AuthenticatedDailyReportReportIdRoute
  AuthenticatedFlagCommentCommentIdRoute: typeof AuthenticatedFlagCommentCommentIdRoute
  AuthenticatedFlagReportReportIdRoute: typeof AuthenticatedFlagReportReportIdRoute
  AuthenticatedReportReportTypePeriodRoute: typeof AuthenticatedReportReportTypePeriodRoute
  AuthenticatedReportMonthlyV2PeriodRoute: typeof AuthenticatedReportMonthlyV2PeriodRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMainRoute: AuthenticatedMainRouteWithChildren,
  AuthenticatedAccountPasswordRoute: AuthenticatedAccountPasswordRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountWithdrawRoute: AuthenticatedAccountWithdrawRoute,
  AuthenticatedAskArchiveRoute: AuthenticatedAskArchiveRoute,
  AuthenticatedAskChatRoute: AuthenticatedAskChatRoute,
  AuthenticatedDailyWriteRoute: AuthenticatedDailyWriteRoute,
  AuthenticatedDetailDateRoute: AuthenticatedDetailDateRouteWithChildren,
  AuthenticatedReportHistoryRoute: AuthenticatedReportHistoryRouteWithChildren,
  AuthenticatedSocialBlockedRoute: AuthenticatedSocialBlockedRoute,
  AuthenticatedSocialRequestsRoute: AuthenticatedSocialRequestsRoute,
  AuthenticatedSocialSearchRoute: AuthenticatedSocialSearchRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAskIndexRoute: AuthenticatedAskIndexRoute,
  AuthenticatedDailyIndexRoute: AuthenticatedDailyIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedDailyReportReportIdRoute: AuthenticatedDailyReportReportIdRoute,
  AuthenticatedFlagCommentCommentIdRoute:
    AuthenticatedFlagCommentCommentIdRoute,
  AuthenticatedFlagReportReportIdRoute: AuthenticatedFlagReportReportIdRoute,
  AuthenticatedReportReportTypePeriodRoute:
    AuthenticatedReportReportTypePeriodRoute,
  AuthenticatedReportMonthlyV2PeriodRoute:
    AuthenticatedReportMonthlyV2PeriodRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface authOnboardingRouteChildren {
  authOnboardingCategoryRoute: typeof authOnboardingCategoryRoute
  authOnboardingIntroRoute: typeof authOnboardingIntroRoute
  authOnboardingProfileRoute: typeof authOnboardingProfileRoute
}

const authOnboardingRouteChildren: authOnboardingRouteChildren = {
  authOnboardingCategoryRoute: authOnboardingCategoryRoute,
  authOnboardingIntroRoute: authOnboardingIntroRoute,
  authOnboardingProfileRoute: authOnboardingProfileRoute,
}

const authOnboardingRouteWithChildren = authOnboardingRoute._addFileChildren(
  authOnboardingRouteChildren,
)

interface authPasswordRouteChildren {
  authPasswordForgotRoute: typeof authPasswordForgotRoute
  authPasswordResetRoute: typeof authPasswordResetRoute
  authPasswordVerifyRoute: typeof authPasswordVerifyRoute
}

const authPasswordRouteChildren: authPasswordRouteChildren = {
  authPasswordForgotRoute: authPasswordForgotRoute,
  authPasswordResetRoute: authPasswordResetRoute,
  authPasswordVerifyRoute: authPasswordVerifyRoute,
}

const authPasswordRouteWithChildren = authPasswordRoute._addFileChildren(
  authPasswordRouteChildren,
)

interface authSignupRouteChildren {
  authSignupEmailRoute: typeof authSignupEmailRoute
  authSignupEmailVerificationRoute: typeof authSignupEmailVerificationRoute
  authSignupPasswordRoute: typeof authSignupPasswordRoute
  authSignupTermsRoute: typeof authSignupTermsRoute
}

const authSignupRouteChildren: authSignupRouteChildren = {
  authSignupEmailRoute: authSignupEmailRoute,
  authSignupEmailVerificationRoute: authSignupEmailVerificationRoute,
  authSignupPasswordRoute: authSignupPasswordRoute,
  authSignupTermsRoute: authSignupTermsRoute,
}

const authSignupRouteWithChildren = authSignupRoute._addFileChildren(
  authSignupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authByeRoute: authByeRoute,
  authLoginRoute: authLoginRoute,
  authOnboardingRoute: authOnboardingRouteWithChildren,
  authPasswordRoute: authPasswordRouteWithChildren,
  authRestoreRoute: authRestoreRoute,
  authSignupRoute: authSignupRouteWithChildren,
  authAuthProviderCallbackRoute: authAuthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
