/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMainRouteImport } from './routes/_authenticated/_main'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authRestoreRouteImport } from './routes/(auth)/restore'
import { Route as authPasswordRouteImport } from './routes/(auth)/password'
import { Route as authOnboardingRouteImport } from './routes/(auth)/onboarding'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authByeRouteImport } from './routes/(auth)/bye'
import { Route as AuthenticatedTodayIndexRouteImport } from './routes/_authenticated/today/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedTodayWriteRouteImport } from './routes/_authenticated/today/write'
import { Route as AuthenticatedTodayReportRouteImport } from './routes/_authenticated/today/report'
import { Route as AuthenticatedAccountWithdrawRouteImport } from './routes/_authenticated/account/withdraw'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAccountPasswordRouteImport } from './routes/_authenticated/account/password'
import { Route as AuthenticatedMainSocialRouteImport } from './routes/_authenticated/_main/social'
import { Route as AuthenticatedMainReportRouteImport } from './routes/_authenticated/_main/report'
import { Route as AuthenticatedMainCalendarRouteImport } from './routes/_authenticated/_main/calendar'
import { Route as authSignupTermsRouteImport } from './routes/(auth)/signup/terms'
import { Route as authSignupPasswordRouteImport } from './routes/(auth)/signup/password'
import { Route as authSignupEmailVerificationRouteImport } from './routes/(auth)/signup/emailVerification'
import { Route as authSignupEmailRouteImport } from './routes/(auth)/signup/email'
import { Route as authPasswordVerifyRouteImport } from './routes/(auth)/password/verify'
import { Route as authPasswordResetRouteImport } from './routes/(auth)/password/reset'
import { Route as authPasswordForgotRouteImport } from './routes/(auth)/password/forgot'
import { Route as authOnboardingProfileRouteImport } from './routes/(auth)/onboarding/profile'
import { Route as authOnboardingIntroRouteImport } from './routes/(auth)/onboarding/intro'
import { Route as authOnboardingCategoryRouteImport } from './routes/(auth)/onboarding/category'
import { Route as authAuthProviderCallbackRouteImport } from './routes/(auth)/auth.$provider.callback'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMainRoute = AuthenticatedMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authRestoreRoute = authRestoreRouteImport.update({
  id: '/(auth)/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const authPasswordRoute = authPasswordRouteImport.update({
  id: '/(auth)/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOnboardingRoute = authOnboardingRouteImport.update({
  id: '/(auth)/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authByeRoute = authByeRouteImport.update({
  id: '/(auth)/bye',
  path: '/bye',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayIndexRoute = AuthenticatedTodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTodayWriteRoute = AuthenticatedTodayWriteRouteImport.update({
  id: '/today/write',
  path: '/today/write',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayReportRoute =
  AuthenticatedTodayReportRouteImport.update({
    id: '/today/report',
    path: '/today/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountWithdrawRoute =
  AuthenticatedAccountWithdrawRouteImport.update({
    id: '/account/withdraw',
    path: '/account/withdraw',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountPasswordRoute =
  AuthenticatedAccountPasswordRouteImport.update({
    id: '/account/password',
    path: '/account/password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMainSocialRoute = AuthenticatedMainSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedMainRoute,
} as any)
const AuthenticatedMainReportRoute = AuthenticatedMainReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedMainRoute,
} as any)
const AuthenticatedMainCalendarRoute =
  AuthenticatedMainCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedMainRoute,
  } as any)
const authSignupTermsRoute = authSignupTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => authSignupRoute,
} as any)
const authSignupPasswordRoute = authSignupPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => authSignupRoute,
} as any)
const authSignupEmailVerificationRoute =
  authSignupEmailVerificationRouteImport.update({
    id: '/emailVerification',
    path: '/emailVerification',
    getParentRoute: () => authSignupRoute,
  } as any)
const authSignupEmailRoute = authSignupEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => authSignupRoute,
} as any)
const authPasswordVerifyRoute = authPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => authPasswordRoute,
} as any)
const authPasswordResetRoute = authPasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => authPasswordRoute,
} as any)
const authPasswordForgotRoute = authPasswordForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => authPasswordRoute,
} as any)
const authOnboardingProfileRoute = authOnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => authOnboardingRoute,
} as any)
const authOnboardingIntroRoute = authOnboardingIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => authOnboardingRoute,
} as any)
const authOnboardingCategoryRoute = authOnboardingCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => authOnboardingRoute,
} as any)
const authAuthProviderCallbackRoute =
  authAuthProviderCallbackRouteImport.update({
    id: '/(auth)/auth/$provider/callback',
    path: '/auth/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bye': typeof authByeRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRouteWithChildren
  '/password': typeof authPasswordRouteWithChildren
  '/restore': typeof authRestoreRoute
  '/signup': typeof authSignupRouteWithChildren
  '/onboarding/category': typeof authOnboardingCategoryRoute
  '/onboarding/intro': typeof authOnboardingIntroRoute
  '/onboarding/profile': typeof authOnboardingProfileRoute
  '/password/forgot': typeof authPasswordForgotRoute
  '/password/reset': typeof authPasswordResetRoute
  '/password/verify': typeof authPasswordVerifyRoute
  '/signup/email': typeof authSignupEmailRoute
  '/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/signup/password': typeof authSignupPasswordRoute
  '/signup/terms': typeof authSignupTermsRoute
  '/calendar': typeof AuthenticatedMainCalendarRoute
  '/report': typeof AuthenticatedMainReportRoute
  '/social': typeof AuthenticatedMainSocialRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/withdraw': typeof AuthenticatedAccountWithdrawRoute
  '/today/report': typeof AuthenticatedTodayReportRoute
  '/today/write': typeof AuthenticatedTodayWriteRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/today': typeof AuthenticatedTodayIndexRoute
  '/auth/$provider/callback': typeof authAuthProviderCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bye': typeof authByeRoute
  '/login': typeof authLoginRoute
  '/onboarding': typeof authOnboardingRouteWithChildren
  '/password': typeof authPasswordRouteWithChildren
  '/restore': typeof authRestoreRoute
  '/signup': typeof authSignupRouteWithChildren
  '/onboarding/category': typeof authOnboardingCategoryRoute
  '/onboarding/intro': typeof authOnboardingIntroRoute
  '/onboarding/profile': typeof authOnboardingProfileRoute
  '/password/forgot': typeof authPasswordForgotRoute
  '/password/reset': typeof authPasswordResetRoute
  '/password/verify': typeof authPasswordVerifyRoute
  '/signup/email': typeof authSignupEmailRoute
  '/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/signup/password': typeof authSignupPasswordRoute
  '/signup/terms': typeof authSignupTermsRoute
  '/calendar': typeof AuthenticatedMainCalendarRoute
  '/report': typeof AuthenticatedMainReportRoute
  '/social': typeof AuthenticatedMainSocialRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/withdraw': typeof AuthenticatedAccountWithdrawRoute
  '/today/report': typeof AuthenticatedTodayReportRoute
  '/today/write': typeof AuthenticatedTodayWriteRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/today': typeof AuthenticatedTodayIndexRoute
  '/auth/$provider/callback': typeof authAuthProviderCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/(auth)/bye': typeof authByeRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/onboarding': typeof authOnboardingRouteWithChildren
  '/(auth)/password': typeof authPasswordRouteWithChildren
  '/(auth)/restore': typeof authRestoreRoute
  '/(auth)/signup': typeof authSignupRouteWithChildren
  '/_authenticated/_main': typeof AuthenticatedMainRouteWithChildren
  '/(auth)/onboarding/category': typeof authOnboardingCategoryRoute
  '/(auth)/onboarding/intro': typeof authOnboardingIntroRoute
  '/(auth)/onboarding/profile': typeof authOnboardingProfileRoute
  '/(auth)/password/forgot': typeof authPasswordForgotRoute
  '/(auth)/password/reset': typeof authPasswordResetRoute
  '/(auth)/password/verify': typeof authPasswordVerifyRoute
  '/(auth)/signup/email': typeof authSignupEmailRoute
  '/(auth)/signup/emailVerification': typeof authSignupEmailVerificationRoute
  '/(auth)/signup/password': typeof authSignupPasswordRoute
  '/(auth)/signup/terms': typeof authSignupTermsRoute
  '/_authenticated/_main/calendar': typeof AuthenticatedMainCalendarRoute
  '/_authenticated/_main/report': typeof AuthenticatedMainReportRoute
  '/_authenticated/_main/social': typeof AuthenticatedMainSocialRoute
  '/_authenticated/account/password': typeof AuthenticatedAccountPasswordRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/withdraw': typeof AuthenticatedAccountWithdrawRoute
  '/_authenticated/today/report': typeof AuthenticatedTodayReportRoute
  '/_authenticated/today/write': typeof AuthenticatedTodayWriteRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/today/': typeof AuthenticatedTodayIndexRoute
  '/(auth)/auth/$provider/callback': typeof authAuthProviderCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bye'
    | '/login'
    | '/onboarding'
    | '/password'
    | '/restore'
    | '/signup'
    | '/onboarding/category'
    | '/onboarding/intro'
    | '/onboarding/profile'
    | '/password/forgot'
    | '/password/reset'
    | '/password/verify'
    | '/signup/email'
    | '/signup/emailVerification'
    | '/signup/password'
    | '/signup/terms'
    | '/calendar'
    | '/report'
    | '/social'
    | '/account/password'
    | '/account/profile'
    | '/account/withdraw'
    | '/today/report'
    | '/today/write'
    | '/account'
    | '/today'
    | '/auth/$provider/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bye'
    | '/login'
    | '/onboarding'
    | '/password'
    | '/restore'
    | '/signup'
    | '/onboarding/category'
    | '/onboarding/intro'
    | '/onboarding/profile'
    | '/password/forgot'
    | '/password/reset'
    | '/password/verify'
    | '/signup/email'
    | '/signup/emailVerification'
    | '/signup/password'
    | '/signup/terms'
    | '/calendar'
    | '/report'
    | '/social'
    | '/account/password'
    | '/account/profile'
    | '/account/withdraw'
    | '/today/report'
    | '/today/write'
    | '/account'
    | '/today'
    | '/auth/$provider/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/bye'
    | '/(auth)/login'
    | '/(auth)/onboarding'
    | '/(auth)/password'
    | '/(auth)/restore'
    | '/(auth)/signup'
    | '/_authenticated/_main'
    | '/(auth)/onboarding/category'
    | '/(auth)/onboarding/intro'
    | '/(auth)/onboarding/profile'
    | '/(auth)/password/forgot'
    | '/(auth)/password/reset'
    | '/(auth)/password/verify'
    | '/(auth)/signup/email'
    | '/(auth)/signup/emailVerification'
    | '/(auth)/signup/password'
    | '/(auth)/signup/terms'
    | '/_authenticated/_main/calendar'
    | '/_authenticated/_main/report'
    | '/_authenticated/_main/social'
    | '/_authenticated/account/password'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/withdraw'
    | '/_authenticated/today/report'
    | '/_authenticated/today/write'
    | '/_authenticated/account/'
    | '/_authenticated/today/'
    | '/(auth)/auth/$provider/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  authByeRoute: typeof authByeRoute
  authLoginRoute: typeof authLoginRoute
  authOnboardingRoute: typeof authOnboardingRouteWithChildren
  authPasswordRoute: typeof authPasswordRouteWithChildren
  authRestoreRoute: typeof authRestoreRoute
  authSignupRoute: typeof authSignupRouteWithChildren
  authAuthProviderCallbackRoute: typeof authAuthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_main': {
      id: '/_authenticated/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedMainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/restore': {
      id: '/(auth)/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof authRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/password': {
      id: '/(auth)/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof authPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/onboarding': {
      id: '/(auth)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof authOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/bye': {
      id: '/(auth)/bye'
      path: '/bye'
      fullPath: '/bye'
      preLoaderRoute: typeof authByeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today/': {
      id: '/_authenticated/today/'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today/write': {
      id: '/_authenticated/today/write'
      path: '/today/write'
      fullPath: '/today/write'
      preLoaderRoute: typeof AuthenticatedTodayWriteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today/report': {
      id: '/_authenticated/today/report'
      path: '/today/report'
      fullPath: '/today/report'
      preLoaderRoute: typeof AuthenticatedTodayReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/withdraw': {
      id: '/_authenticated/account/withdraw'
      path: '/account/withdraw'
      fullPath: '/account/withdraw'
      preLoaderRoute: typeof AuthenticatedAccountWithdrawRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/password': {
      id: '/_authenticated/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthenticatedAccountPasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_main/social': {
      id: '/_authenticated/_main/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedMainSocialRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/_main/report': {
      id: '/_authenticated/_main/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedMainReportRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/_authenticated/_main/calendar': {
      id: '/_authenticated/_main/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedMainCalendarRouteImport
      parentRoute: typeof AuthenticatedMainRoute
    }
    '/(auth)/signup/terms': {
      id: '/(auth)/signup/terms'
      path: '/terms'
      fullPath: '/signup/terms'
      preLoaderRoute: typeof authSignupTermsRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/password': {
      id: '/(auth)/signup/password'
      path: '/password'
      fullPath: '/signup/password'
      preLoaderRoute: typeof authSignupPasswordRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/emailVerification': {
      id: '/(auth)/signup/emailVerification'
      path: '/emailVerification'
      fullPath: '/signup/emailVerification'
      preLoaderRoute: typeof authSignupEmailVerificationRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/signup/email': {
      id: '/(auth)/signup/email'
      path: '/email'
      fullPath: '/signup/email'
      preLoaderRoute: typeof authSignupEmailRouteImport
      parentRoute: typeof authSignupRoute
    }
    '/(auth)/password/verify': {
      id: '/(auth)/password/verify'
      path: '/verify'
      fullPath: '/password/verify'
      preLoaderRoute: typeof authPasswordVerifyRouteImport
      parentRoute: typeof authPasswordRoute
    }
    '/(auth)/password/reset': {
      id: '/(auth)/password/reset'
      path: '/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof authPasswordResetRouteImport
      parentRoute: typeof authPasswordRoute
    }
    '/(auth)/password/forgot': {
      id: '/(auth)/password/forgot'
      path: '/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof authPasswordForgotRouteImport
      parentRoute: typeof authPasswordRoute
    }
    '/(auth)/onboarding/profile': {
      id: '/(auth)/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof authOnboardingProfileRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/(auth)/onboarding/intro': {
      id: '/(auth)/onboarding/intro'
      path: '/intro'
      fullPath: '/onboarding/intro'
      preLoaderRoute: typeof authOnboardingIntroRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/(auth)/onboarding/category': {
      id: '/(auth)/onboarding/category'
      path: '/category'
      fullPath: '/onboarding/category'
      preLoaderRoute: typeof authOnboardingCategoryRouteImport
      parentRoute: typeof authOnboardingRoute
    }
    '/(auth)/auth/$provider/callback': {
      id: '/(auth)/auth/$provider/callback'
      path: '/auth/$provider/callback'
      fullPath: '/auth/$provider/callback'
      preLoaderRoute: typeof authAuthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMainRouteChildren {
  AuthenticatedMainCalendarRoute: typeof AuthenticatedMainCalendarRoute
  AuthenticatedMainReportRoute: typeof AuthenticatedMainReportRoute
  AuthenticatedMainSocialRoute: typeof AuthenticatedMainSocialRoute
}

const AuthenticatedMainRouteChildren: AuthenticatedMainRouteChildren = {
  AuthenticatedMainCalendarRoute: AuthenticatedMainCalendarRoute,
  AuthenticatedMainReportRoute: AuthenticatedMainReportRoute,
  AuthenticatedMainSocialRoute: AuthenticatedMainSocialRoute,
}

const AuthenticatedMainRouteWithChildren =
  AuthenticatedMainRoute._addFileChildren(AuthenticatedMainRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMainRoute: typeof AuthenticatedMainRouteWithChildren
  AuthenticatedAccountPasswordRoute: typeof AuthenticatedAccountPasswordRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountWithdrawRoute: typeof AuthenticatedAccountWithdrawRoute
  AuthenticatedTodayReportRoute: typeof AuthenticatedTodayReportRoute
  AuthenticatedTodayWriteRoute: typeof AuthenticatedTodayWriteRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedTodayIndexRoute: typeof AuthenticatedTodayIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMainRoute: AuthenticatedMainRouteWithChildren,
  AuthenticatedAccountPasswordRoute: AuthenticatedAccountPasswordRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountWithdrawRoute: AuthenticatedAccountWithdrawRoute,
  AuthenticatedTodayReportRoute: AuthenticatedTodayReportRoute,
  AuthenticatedTodayWriteRoute: AuthenticatedTodayWriteRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedTodayIndexRoute: AuthenticatedTodayIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface authOnboardingRouteChildren {
  authOnboardingCategoryRoute: typeof authOnboardingCategoryRoute
  authOnboardingIntroRoute: typeof authOnboardingIntroRoute
  authOnboardingProfileRoute: typeof authOnboardingProfileRoute
}

const authOnboardingRouteChildren: authOnboardingRouteChildren = {
  authOnboardingCategoryRoute: authOnboardingCategoryRoute,
  authOnboardingIntroRoute: authOnboardingIntroRoute,
  authOnboardingProfileRoute: authOnboardingProfileRoute,
}

const authOnboardingRouteWithChildren = authOnboardingRoute._addFileChildren(
  authOnboardingRouteChildren,
)

interface authPasswordRouteChildren {
  authPasswordForgotRoute: typeof authPasswordForgotRoute
  authPasswordResetRoute: typeof authPasswordResetRoute
  authPasswordVerifyRoute: typeof authPasswordVerifyRoute
}

const authPasswordRouteChildren: authPasswordRouteChildren = {
  authPasswordForgotRoute: authPasswordForgotRoute,
  authPasswordResetRoute: authPasswordResetRoute,
  authPasswordVerifyRoute: authPasswordVerifyRoute,
}

const authPasswordRouteWithChildren = authPasswordRoute._addFileChildren(
  authPasswordRouteChildren,
)

interface authSignupRouteChildren {
  authSignupEmailRoute: typeof authSignupEmailRoute
  authSignupEmailVerificationRoute: typeof authSignupEmailVerificationRoute
  authSignupPasswordRoute: typeof authSignupPasswordRoute
  authSignupTermsRoute: typeof authSignupTermsRoute
}

const authSignupRouteChildren: authSignupRouteChildren = {
  authSignupEmailRoute: authSignupEmailRoute,
  authSignupEmailVerificationRoute: authSignupEmailVerificationRoute,
  authSignupPasswordRoute: authSignupPasswordRoute,
  authSignupTermsRoute: authSignupTermsRoute,
}

const authSignupRouteWithChildren = authSignupRoute._addFileChildren(
  authSignupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  authByeRoute: authByeRoute,
  authLoginRoute: authLoginRoute,
  authOnboardingRoute: authOnboardingRouteWithChildren,
  authPasswordRoute: authPasswordRouteWithChildren,
  authRestoreRoute: authRestoreRoute,
  authSignupRoute: authSignupRouteWithChildren,
  authAuthProviderCallbackRoute: authAuthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
